import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  recipeCard: {
    flexDirection: 'row',
    backgroundColor: '#121214',
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 0.5,
    borderColor: 'rgba(212, 175, 55, 0.1)',
    height: 150,
  },
  recipeImage: { width: 150, height: 150 },
  recipeContent: { flex: 1, padding: 20, justifyContent: 'space-between' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardArea: { color: COLORS.secondary, fontSize: 8, fontWeight: '800', letterSpacing: 2 },
  recipeTitle: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '300',
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    lineHeight: 22,
  },
  cardFooter: { flexDirection: 'row' },
  luxuryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.03)',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  luxuryTagText: { color: 'rgba(255,255,255,0.4)', fontSize: 7, fontWeight: '800', letterSpacing: 1 },
  cuisineCard: {
    height: 280,
    backgroundColor: COLORS.primary,
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 24,
    borderWidth: 0.5,
    borderColor: 'rgba(5,5,5,0.1)',
  },
  cuisineImage: { width: '100%', height: '100%', opacity: 0.7 },
  cuisineOverlay: {
    ...StyleSheet.absoluteFillObject,
    padding: 24,
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  cuisineTop: { flexDirection: 'row', justifyContent: 'space-between' },
  flag: { width: 30, height: 18, borderRadius: 0, opacity: 0.8 },
  recipeCounter: {
    backgroundColor: COLORS.secondary,
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  counterText: { color: COLORS.primary, fontSize: 9, fontWeight: '900' },
  cuisinePre: { color: COLORS.secondary, fontSize: 8, fontWeight: '800', letterSpacing: 3, marginBottom: 4 },
  cuisineTitle: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '300',
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    letterSpacing: 1,
  },
});
