import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: { paddingBottom: 100 },
  heroFrame: { width: '100%', overflow: 'hidden', position: 'relative' },
  heroImage: { width: '100%', height: '100%' },
  heroShadow: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.3)' },
  floatingAction: {
    position: 'absolute',
    bottom: -25,
    right: 32,
    backgroundColor: COLORS.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.5,
    borderColor: COLORS.secondary,
    elevation: 8,
  },
  ribbon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
    paddingVertical: 60,
  },
  ribbonItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  ribbonText: { fontSize: 10, color: 'rgba(255,255,255,0.5)', fontWeight: '800', letterSpacing: 2 },
  ribbonDot: { width: 3, height: 3, borderRadius: 1.5, backgroundColor: 'rgba(212, 175, 55, 0.4)' },
  title: {
    fontSize: 42,
    fontWeight: '300',
    color: '#FFF',
    textAlign: 'center',
    paddingHorizontal: 24,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    letterSpacing: 2,
    marginBottom: 20,
  },
  titleDivider: {
    width: 40,
    height: 1,
    backgroundColor: COLORS.secondary,
    alignSelf: 'center',
    marginBottom: 60,
  },
  contentLayout: { paddingHorizontal: 32 },
  desktopRow: { flexDirection: 'row' },
  desktopCol: { flex: 1 },
  section: { marginBottom: 60 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '300',
    color: COLORS.secondary,
    letterSpacing: 4,
    marginBottom: 32,
    textTransform: 'uppercase',
  },
  ingredientsList: { gap: 16 },
  ingredientRow: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  ingDot: { width: 6, height: 1, backgroundColor: COLORS.secondary },
  ingText: { color: 'rgba(255,255,255,0.7)', fontSize: 14, fontWeight: '400', lineHeight: 22 },
  stepBlock: { marginBottom: 40 },
  stepHeader: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 12 },
  stepIndex: { color: COLORS.secondary, fontSize: 12, fontWeight: '900', letterSpacing: 2 },
  stepLine: { flex: 1, height: 0.5, backgroundColor: 'rgba(255,255,255,0.05)' },
  stepContent: { color: 'rgba(255,255,255,0.6)', lineHeight: 28, fontSize: 15, fontWeight: '400' },
});
