/**
 * Donnees locales : correspondance nom de zone / cuisine (TheMealDB) vers URL de drapeau.
 * Utilise dans ExplorePage / Card pour enrichir les cartes cuisines hors API flags.
 */
export const cuisineData = [
  { name: "Algerian",     code: "dz", flag: "https://flagcdn.com/w80/dz.png" },
  { name: "American",     code: "us", flag: "https://flagcdn.com/w80/us.png" },
  { name: "Argentinian",  code: "ar", flag: "https://flagcdn.com/w80/ar.png" },
  { name: "Australian",    code: "au", flag: "https://flagcdn.com/w80/au.png" },
  { name: "British",      code: "gb", flag: "https://flagcdn.com/w80/gb.png" },
  { name: "Canadian",     code: "ca", flag: "https://flagcdn.com/w80/ca.png" },
  { name: "Chinese",      code: "cn", flag: "https://flagcdn.com/w80/cn.png" },
  { name: "Croatian",     code: "hr", flag: "https://flagcdn.com/w80/hr.png" },
  { name: "Dutch",        code: "nl", flag: "https://flagcdn.com/w80/nl.png" },
  { name: "Egyptian",     code: "eg", flag: "https://flagcdn.com/w80/eg.png" },
  { name: "Filipino",     code: "ph", flag: "https://flagcdn.com/w80/ph.png" },
  { name: "French",       code: "fr", flag: "https://flagcdn.com/w80/fr.png" },
  { name: "Greek",        code: "gr", flag: "https://flagcdn.com/w80/gr.png" },
  { name: "Indian",       code: "in", flag: "https://flagcdn.com/w80/in.png" },
  { name: "Irish",        code: "ie", flag: "https://flagcdn.com/w80/ie.png" },
  { name: "Italian",      code: "it", flag: "https://flagcdn.com/w80/it.png" },
  { name: "Jamaican",     code: "jm", flag: "https://flagcdn.com/w80/jm.png" },
  { name: "Japanese",     code: "jp", flag: "https://flagcdn.com/w80/jp.png" },
  { name: "Kenyan",       code: "ke", flag: "https://flagcdn.com/w80/ke.png" },
  { name: "Malaysian",    code: "my", flag: "https://flagcdn.com/w80/my.png" },
  { name: "Mexican",      code: "mx", flag: "https://flagcdn.com/w80/mx.png" },
  { name: "Moroccan",     code: "ma", flag: "https://flagcdn.com/w80/ma.png" },
  { name: "New Zealander",code: "nz", flag: "https://flagcdn.com/w80/nz.png" },
  { name: "Norwegian",    code: "no", flag: "https://flagcdn.com/w80/no.png" },
  { name: "Polish",       code: "pl", flag: "https://flagcdn.com/w80/pl.png" },
  { name: "Portuguese",   code: "pt", flag: "https://flagcdn.com/w80/pt.png" },
  { name: "Russian",      code: "ru", flag: "https://flagcdn.com/w80/ru.png" },
  { name: "Saudi Arabian", code: "sa", flag: "https://flagcdn.com/w80/sa.png" },
  { name: "Slovakian",     code: "sk", flag: "https://flagcdn.com/w80/sk.png" },
  { name: "Spanish",      code: "es", flag: "https://flagcdn.com/w80/es.png" },
  { name: "Syrian",        code: "sy", flag: "https://flagcdn.com/w80/sy.png" },
  { name: "Thai",         code: "th", flag: "https://flagcdn.com/w80/th.png" },
  { name: "Tunisian",     code: "tn", flag: "https://flagcdn.com/w80/tn.png" },
  { name: "Turkish",      code: "tr", flag: "https://flagcdn.com/w80/tr.png" },
  { name: "Ukrainian",    code: "ua", flag: "https://flagcdn.com/w80/ua.png" },
  { name: "Uruguayan",     code: "uy", flag: "https://flagcdn.com/w80/uy.png" },
  { name: "Venezulan",     code: "ve", flag: "https://flagcdn.com/w80/ve.png" },
  { name: "Vietnamese",   code: "vn", flag: "https://flagcdn.com/w80/vn.png" },
  { name: "Unknown",      code: null, flag: null },
];
