import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: { paddingBottom: 60 },
  heroSection: { height: 560, borderRadius: 0, overflow: 'hidden', marginBottom: 50 },
  heroOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(5,5,5,0.7)' },
  heroContent: { flex: 1, padding: 32, justifyContent: 'center', paddingTop: 100 },
  prestigeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderLeftWidth: 1,
    borderLeftColor: COLORS.secondary,
    paddingLeft: 12,
    marginBottom: 24,
  },
  crownDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: COLORS.secondary },
  prestigeText: { color: COLORS.secondary, fontSize: 10, fontWeight: '800', letterSpacing: 4 },
  heroTitle: {
    color: '#FFF',
    fontSize: 42,
    fontWeight: '300',
    lineHeight: 52,
    marginBottom: 24,
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
    letterSpacing: 2,
  },
  heroSub: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    lineHeight: 24,
    maxWidth: '85%',
    marginBottom: 40,
    fontWeight: '400',
  },
  primaryBtn: {
    backgroundColor: COLORS.secondary,
    paddingVertical: 18,
    paddingHorizontal: 28,
    borderRadius: 0,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 12,
  },
  primaryBtnText: { color: COLORS.primary, fontWeight: '900', fontSize: 11, letterSpacing: 2 },
  section: { paddingHorizontal: 24, marginBottom: 50 },
  sectionHeader: { marginBottom: 24 },
  sectionPre: { color: COLORS.secondary, fontSize: 9, fontWeight: '800', letterSpacing: 4, marginBottom: 8 },
  sectionTitle: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '300',
    fontFamily: Platform.OS === 'ios' ? 'Times New Roman' : 'serif',
  },
  regionScroll: { gap: 16 },
  regionCard: {
    width: 160,
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderRadius: 2,
    borderWidth: 0.5,
    borderColor: 'rgba(212, 175, 55, 0.1)',
  },
  regionIconBox: { marginBottom: 16 },
  regionName: { color: '#FFF', fontSize: 14, fontWeight: '700', marginBottom: 4 },
  regionDesc: { color: 'rgba(255,255,255,0.4)', fontSize: 9, fontWeight: '500' },
  statsRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.01)',
    paddingVertical: 32,
    borderRadius: 2,
    borderWidth: 0.5,
    borderColor: 'rgba(212, 175, 55, 0.1)',
  },
  statBox: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  statValue: { color: '#FFF', fontSize: 28, fontWeight: '300', marginBottom: 4, fontFamily: 'serif' },
  statLabel: { color: 'rgba(255,255,255,0.3)', fontSize: 8, fontWeight: '900', letterSpacing: 2 },
  statDivider: {
    width: 0.5,
    height: '60%',
    backgroundColor: 'rgba(212, 175, 55, 0.2)',
    alignSelf: 'center',
  },
});
